"$schema"="https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = false
version = 4

[[blocks]]
type = "prompt"
alignment = "left"

[[blocks.segments]]
background = "#470079"
style = "diamond"
leading_diamond = "‚ï≠‚îÄ\ue285\ue0d4"
template = " {{ if .WSL }}WSL @ {{ end }}{{.Icon}} "
type = "os"


[blocks.segments.options]
linux = "<#e7fcaa>\ue712</>"
macos = "<#cae7f3>\ue711</>"
windows = "<#74d5ff>\ue70f</>"


[[blocks.segments]]
type = "shell"
style = "diamond"
background = "#470079"
template = " \uf120 {{ .Name }} "

[[blocks.segments]]
type = "root"
style = "powerline"
background = "#ef5350"
foreground = "#ffffff"
template = "<parentBackground>\ue0b0</>‚ö†Ô∏è  "


[[blocks.segments]]
type = "git"
style = "powerline"
powerline_symbol = "\ue0b0"
leading_powerline_symbol = "\ue285\ue0d4"

background = "#40c4ff"
foreground = "#000000"

template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#ef5350> \uf046 {{ .Staging.String }}</>{{ end }} "
background_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}#ffeb95{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#c5e478{{ end }}",
    "{{ if gt .Ahead 0 }}#C792EA{{ end }}",
    "{{ if gt .Behind 0 }}#C792EA{{ end }}"
]

[blocks.segments.options]
branch_icon = "ÓÇ† "
fetch_status= true
fetch_upstream_icon = true


[[blocks]]
type = "prompt"
alignment = "right"

[[blocks.segments]]
type = "time"
style = "diamond"
background = "#470079"
foreground = "#ffffff"
invert_powerline = true
leading_diamond = "\ue0b2"
trailing_diamond = "\ue0b4"
template = " \uf073 {{ .CurrentDate | date .Format }} "
[blocks.segments.options]
time_format = "_2,15:04"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "text"
style = "plain"
foreground = "#470079"
template = "‚îü‚îÄ"


[[blocks.segments]]
type = "path"
template = "üìÅ {{ .Path }} "
style = "powerline"
powerline_symbol = "\ue0b0"
leading_powerline_symbol = "ÓÇ≤"
foreground = "#ffffff"
background = "#00182c"


[blocks.segments.options]
style = "agnoster"
folder_icon = ".."
home_icon = "üèöÔ∏è"
folder_separator_icon = "\ue216"

[blocks.segments.options.mapped_locations]
"C:\\temp" = "‚åõ "
"D:\\sol" = "‚òÄÔ∏è "
"J:\\Repos\\Github\\dotfiles" = "üßë‚Äçüíª"

[[blocks]]
type = "prompt"
alignment = "right"

[[blocks.segments]]
background = "#303030"
foreground = "#3C873A"
leading_diamond = "\ue0b6"
style = "diamond"
template = "\ue718 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}"
trailing_diamond = " \ue0b4"
type = "node"

[blocks.segments.options]
fetch_package_manager = true
npm_icon = " <#cc3a3a>\ue5fa</> "
yarn_icon = " <#348cba>\ue6a7</>"

[[blocks.segments]]
background = "#306998"
foreground = "#FFE873"
leading_diamond = "\ue0b6"
style = "diamond"
template = "\ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}"
trailing_diamond = " \ue0b4"
type = "python"

[[blocks.segments]]
background = "#0e8ac8"
foreground = "#ffffff"
leading_diamond = "\ue0b6"
style = "diamond"
template = "\ue738 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
trailing_diamond = " \ue0b4"
type = "java"

[[blocks.segments]]
background = "#0e0e0e"
foreground = "#0d6da8"
leading_diamond = "\ue0b6"
style = "diamond"
template = "\ue77f {{ if .Unsupported }}\uf071{{ else }}{{ .Full }}{{ end }}"
trailing_diamond = " \ue0b4"
type = "dotnet"

[[blocks.segments]]
background = "#ffffff"
foreground = "#06aad5"
leading_diamond = "\ue0b6"
style = "diamond"
template = "\ue626 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
trailing_diamond = " \ue0b4"
type = "go"

[[blocks.segments]]
background = "#f3f0ec"
foreground = "#925837"
leading_diamond = "\ue0b6"
style = "diamond"
template = "\ue7a8 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
trailing_diamond = " \ue0b4"
type = "rust"

[[blocks.segments]]
background = "#e1e8e9"
foreground = "#055b9c"
leading_diamond = " \ue0b6"
style = "diamond"
template = "\ue798 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
trailing_diamond = " \ue0b4"
type = "dart"

[[blocks.segments]]
background = "#ffffff"
foreground = "#ce092f"
leading_diamond = " \ue0b6"
style = "diamond"
template = "\ue753 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
trailing_diamond = " \ue0b4"
type = "angular"

[[blocks.segments]]
background = "#ffffff"
foreground = "#de1f84"
leading_diamond = " \ue0b6"
style = "diamond"
template = "Œ± {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
trailing_diamond = " \ue0b4"
type = "aurelia"

[[blocks.segments]]
background = "#1e293b"
foreground = "#ffffff"
leading_diamond = " \ue0b6"
style = "diamond"
template = "{{ if .Error }}{{ .Error }}{{ else }}Nx {{ .Full }}{{ end }}"
trailing_diamond = " \ue0b4"
type = "nx"

[[blocks.segments]]
background = "#945bb3"
foreground = "#359a25"
leading_diamond = " \ue0b6"
style = "diamond"
template = "<#ca3c34>\ue624</> {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
trailing_diamond = " \ue0b4"
type = "julia"

[[blocks.segments]]
background = "#ffffff"
foreground = "#9c1006"
leading_diamond = "\ue0b6"
style = "diamond"
template = "\ue791 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
trailing_diamond = " \ue0b4"
type = "ruby"

[[blocks.segments]]
background = "#ffffff"
foreground = "#5398c2"
leading_diamond = "\ue0b6"
style = "diamond"
template = "\uf104<#f5bf45>\uf0e7</>\uf105 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
trailing_diamond = " \ue0b4"
type = "azfunc"

[[blocks.segments]]
background = "#565656"
foreground = "#faa029"
leading_diamond = "\ue0b6"
style = "diamond"
template = "\ue7ad {{.Profile}}{{if .Region}}@{{.Region}}{{end}}"
trailing_diamond = " \ue0b4"
type = "aws"

[[blocks.segments]]
background = "#316ce4"
foreground = "#ffffff"
leading_diamond = "\ue0b6"
style = "diamond"
template = "\uf308 {{.Context}}{{if .Namespace}} - {{.Namespace}}{{end}}"
trailing_diamond = "\ue0b4"
type = "kubectl"


[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
style = "plain"
type = "text"
template = "‚îó‚îÅ"
foreground = "#470079"

[[blocks.segments]]
style = "plain"
type = "status"
foreground = "#e0f8ff"
template = "\ue285\ueab6 "
foreground_templates = ["{{ if gt .Code 0 }}#ef5350{{ end }}"]

[blocks.segments.options]
always_enabled = true
